quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=username
quarkus.datasource.password=password

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hibernate_orm_test
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.database.generation=drop-and-create

mp.jwt.verify.publickey.location=https://raw.githubusercontent.com/eldermoraes/unipds/main/jwt-token/quarkus.jwt.pub
mp.jwt.verify.issuer=https://quarkus.io/using-jwt-rbac

quarkus.datasource.jdbc.telemetry=true